### ISSUE TITLE
Js and SignalR are didn't work

### ISSUE THREAD

**Issue by kadirkalkan** [kadirkalkan/PragmaLinq#1]
When i try to click one of Index.cshtml buttons. Both of .click methods are working together on Javascript.
But with that at server side(BitcoinHub.cs) trade method doesn't invoke !

**Comment by ssczo** [comment]
Change it to:
$(document).ready(function () {
                var bitcoinHub = $.connection.bitcoinHub;
          
                bitcoinHub.client.sendRate = function (rate) {
                    $("#currentRate").html(rate.value + " ₺");
                    $("#bitcoinBuy").val(rate.value);
                    $("#bitcoinSell").val(rate.value - 5);
                };
                $.connection.hub.start().done(function(){
				      setInterval((function () {
                    bitcoinHub.server.createRate();
                }), 3000);
				  $("#aBitcoin").change(function () {
                        var tl = document.getElementById("bitcoinBuy").value;
                        var btc = document.getElementById("aBitcoin").value;
                        $("#aTotal").val(parseFloat(tl) * parseFloat(btc));
                    });
                    $("#sBitcoin").change(function () {
                        var tl = document.getElementById("bitcoinSell").value;
                        var btc = document.getElementById("sBitcoin").value;
                        $("#sTotal").val(parseFloat(tl) * parseFloat(btc));
                    });})
            });

**Comment by kadirkalkan** [comment]
but those are about textboxes my issue is about with buttons.click
and Btw when i try to this code createRate isn't work too

**Comment by kadirkalkan** [comment]
All Script Block : 
`  <script>
            $(document).ready(function () {
                var bitcoinHub = $.connection.bitcoinHub;
                bitcoinHub.client.sendRate = function (rate) {
                    $("#currentRate").html(rate.value + " ₺");
                    $("#bitcoinBuy").val(rate.value);
                    $("#bitcoinSell").val(rate.value - 5);
                };

                $("#btnBuy").click(function () {
                    var tl = document.getElementById("bitcoinBuy").value;
                    var btc = document.getElementById("aBitcoin").value;
                    var total = document.getElementById("aTotal").value;
                    bitcoinHub.server.trade("sell",@Model.user, tl, btc, total);

                });

                $("#btnSell").onclick(function () {
                    var tl = document.getElementById("bitcoinSell").value;
                    var btc = document.getElementById("sBitcoin").value;
                    var total = document.getElementById("sTotal").value;
                    bitcoinHub.server.trade("sell",@Model.user,tl,btc,total);
                });

                $.connection.hub.start().done(function() {
                    setInterval((function() {
                            bitcoinHub.server.createRate();
                        }),
                        3000);
                    $("#aBitcoin").change(function() {
                        var tl = document.getElementById("bitcoinBuy").value;
                        var btc = document.getElementById("aBitcoin").value;
                        $("#aTotal").val(parseFloat(tl) * parseFloat(btc));
                    });
                    $("#sBitcoin").change(function() {
                        var tl = document.getElementById("bitcoinSell").value;
                        var btc = document.getElementById("sBitcoin").value;
                        $("#sTotal").val(parseFloat(tl) * parseFloat(btc));
                    });
                    bitcoinHub.client.broadcastSell = function (model) {
                        //   $("#sellGrid").append("<li>"+model.Sell+"</li>");
                    };
                    bitcoinHub.client.broadcastPurchase = function (model) {
                        // $("#buyGrid").append("<li>"+model.Buy+"</li>");
                    };
                });
            });
        </script>`

**Comment by ssczo** [comment]
` <script>
$(document).ready(function () {
var bitcoinHub = $.connection.bitcoinHub;


          
            $.connection.hub.start().done(function() {

  $("#btnBuy").click(function () {
                var tl = document.getElementById("bitcoinBuy").value;
                var btc = document.getElementById("aBitcoin").value;
                var total = document.getElementById("aTotal").value;
                bitcoinHub.server.trade("sell",@Model.user, tl, btc, total);

            });

            $("#btnSell").onclick(function () {
                var tl = document.getElementById("bitcoinSell").value;
                var btc = document.getElementById("sBitcoin").value;
                var total = document.getElementById("sTotal").value;
                bitcoinHub.server.trade("sell",@Model.user,tl,btc,total);
            });

                setInterval((function() {
                        bitcoinHub.server.createRate();
                    }),
                    3000);
                $("#aBitcoin").change(function() {
                    var tl = document.getElementById("bitcoinBuy").value;
                    var btc = document.getElementById("aBitcoin").value;
                    $("#aTotal").val(parseFloat(tl) * parseFloat(btc));
                });
                $("#sBitcoin").change(function() {
                    var tl = document.getElementById("bitcoinSell").value;
                    var btc = document.getElementById("sBitcoin").value;
                    $("#sTotal").val(parseFloat(tl) * parseFloat(btc));
                });
                bitcoinHub.client.broadcastSell = function (model) {
                    //   $("#sellGrid").append("<li>"+model.Sell+"</li>");
                };
                bitcoinHub.client.broadcastPurchase = function (model) {
                    // $("#buyGrid").append("<li>"+model.Buy+"</li>");
                };

bitcoinHub.client.sendRate = function (rate) {
$("#currentRate").html(rate.value + " ₺");
$("#bitcoinBuy").val(rate.value);
$("#bitcoinSell").val(rate.value - 5);
};
            });
        });
    </script>`

**Comment by ssczo** [comment]
Why is two times bitcoinHub.server.trade("sell",@Model.user, tl, btc, total);   "sell"  also here
 bitcoinHub.server.trade("sell",@Model.user,tl,btc,total);

**Comment by kadirkalkan** [comment]
because hub method has a switch case ("sell" or "buy"). i fix it like 
`  
   bitcoinHub.server.trade("buy", @Model.user, tl, btc, total);
   bitcoinHub.server.trade("sell", @Model.user, tl, btc, total);
`

**Comment by kadirkalkan** [comment]
Kritik Güncelleme commit solved Problem Description explain source of exception.
